# VMs to be created by Vagrant using following values
# default cpu=1, mem=512, box=debian/buster64 values will used if they are missing from nodes/hostname.
# If no 'ip' is defined then Vagrant creates the default adapter 1 using nat.
nodes:
  - hostname: 'test1'
    ip: '192.170.1.20'
    ip2: '192.170.2.20'
    cpu: '1'
    mem: '1024'
    box: 'debian/buster64'
  - hostname: test2
    ip: '192.170.1.21'
    cpu: '2'
    mem: '1024'
    box: 'debian/stretch64'
  - hostname: 'test3'
    ip: '192.170.1.22'
    ip2: '192.170.2.22'
    ip3: '192.170.3.22'
    ip4: '192.170.4.22'
    cpu: '1'
    box: 'debian/buster64'  
  - hostname: 'test4'

# Ansible user name for Vagrant to use
ansible_user: vagrant
ansible_user_password: 'vagrant'

# Dir name under home dir to store ssh keys
ssh_key_dir: 'test_ssh_keys'
# Actual private key file name to be created
ssh_key: 'test_id_rsa'
# Ansible intentory to use
ansible_inventory_path: "inventory/hosts"
# Ansible vault password file
ansible_vault_password_file: "vault_pass/vault_pass.txt"
# Ansible cfg file path
ansible_hostfile: "ansible.cfg"
# Ansible play to play
ansible_playbook: "vagarant_init_play.yml"
# Ansible limit to use
ansible_limit: "all"