---
- name: Add the user 'ansible' with a bash shell, appending the group 'sudo' to the user's groups
  user:
    name: "{{ ansible_user_name }}"
    password: "{{ ansible_user_password | password_hash('sha512') }}"
    update_password: 'always'
    create_home: yes
    generate_ssh_key: yes
    ssh_key_type: 'rsa'
    ssh_key_bits: 4096
    shell: '/bin/bash'
    home: "/home/{{ ansible_user_name }}"
    groups: 'sudo'
    system: 'no'
    append: yes
  become: yes