---
# Install Needed minimum software
- name: Install Needed minimum software
  import_tasks: package.yml

- name: Set locale
  import_tasks: locale.yml

# Create user for ansible to use
- name: Create user for Ansible
  import_tasks: ansible_user.yml

- debug:
    var: ansible_ssh_public_key_file

- name: Set authorized key taken from file for the Ansible user
  authorized_key:
    user: "{{ ansible_user_name }}"
    state: present
    key: "{{ lookup('file', ansible_ssh_public_key_file) }}"



